# General Defaults
SECRETS_REPO="$HOME/Projects/glabs-secrets"
LATHE_THEME='mono'

# CT Quick Deploy
CT_STORAGE="local-lvm"
CT_MEMORY=512
CT_CORES=1
CT_DISK=8
CT_BRIDGE="vmbr0"
CT_TEMPLATE="debian-12-standard"
PVE_HOST="pve"